### ISSUE TITLE
Có thẻ fine tuning mô hình đã fine tuned được không?

### ISSUE THREAD

**Issue by salforis** [khanld/Vietnamese-ASR-Released-Model#1]
Xin chào! Cho mình hỏi ngu chút là có thể dùng mô hình đã fine tuned (ví dụ như mô hình của bạn) để  fine tune tiếp bằng dữ liệu khác thì có chạy được không? Mình cảm ơn

**Comment by khanld** [comment]
vẫn được bạn nhé, trong file train.py bạn load processor và model mình xuống, rồi finetune tiếp trên data của bạn là được.
`processor = Wav2Vec2Processor.from_pretrained("khanhld/wav2vec2-base-vietnamese-160h")
`
`    model = Wav2Vec2ForCTC.from_pretrained(
        "khanhld/wav2vec2-base-vietnamese-160h", 
        ctc_loss_reduction="mean", 
        pad_token_id=processor.tokenizer.pad_token_id,
        vocab_size=len(processor.tokenizer),
        gradient_checkpointing=False
    )`

**Comment by salforis** [comment]
Cám ơn bạn
